version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    container_name: elastic-research
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    env_file:
      - .env
    ports:
      - "127.0.0.1:${elastic_port}:9200"