version: '3'

services:
  mongo:
    ports:
      - "${mongo_port}:27017"
    image: mongo:6.0.9-jammy
    container_name: mongo-research
    restart: always
    logging:
      options:
        max-size: 1g
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${mongo_user}
      - MONGO_INITDB_ROOT_PASSWORD=${mongo_pass}